theme: jekyll-theme-slate
title: Welcome to TrinadhK blog
description: My learnings with Technology(Mostly Microsoft) as a Cloud Solution Architect at MSFT and at a personal level as tech enthusiast.
